# accelerate_config.yaml
# Configuration for Hugging Face Accelerate

compute_environment: "LOCAL_MACHINE"
distributed_type: "MULTI_GPU"
downcast_bf16: "no"
gpu_ids: "all"
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: "main"
mixed_precision: "fp16" # or "bf16" if your hardware supports it well
num_machines: 2
num_processes: 4 # 2 nodes * 2 GPUs/node
rdzv_backend: "static"
same_network: true
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
